name: Python package

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10.08^]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'  

      - name: Setup and Install Poetry
        uses: pronovic/setup-poetry@v1.2.0


      - name: Create and activate Poetry shell
        run: |
          source $(poetry env info --path)/bin/activate
          poetry install

      - name: Add PYTHONPATH (Unix)
        if: runner.os != 'Windows'
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      - name: Add PYTHONPATH (Windows)
        if: runner.os == 'Windows'
        run: echo "PYTHONPATH=${PYTHONPATH};${{ github.workspace }}" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Run tests
        run: poetry run python -m unittest discover

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'