name: Python package

on:
  push:
    branches:
      - main 

jobs:
  build:

    runs-on: ubuntu-latest
    
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'  

      - name: Setup and Install Poetry
          uses: pronovic/setup-poetry@v1.2.0


      - name: Create and activate Poetry shell
        run: |
          poetry install
          source $(poetry env info --path)/bin/activate


      - name: Run tests
        run: poetry run python -m unittest discover

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'